# Generated by Django 2.2.6 on 2019-10-25 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTPAPI', '0003_auto_20191025_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='phone',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?[0-9]{9,15}$')], verbose_name='phone number'),
        ),
    ]
